api_platform:
    title: Resonance API
    description: API for the Resonance project
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
