
services:
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: resonance_database
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw*
  app:
    image: php:8.2-fpm
    container_name: resonance_api
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      database:
        condition: service_healthy
    command: >
      sh -c "apt-get update &&
             apt-get install -y git unzip libpq-dev &&
             docker-php-ext-install pdo pdo_pgsql &&
             php-fpm"
  nginx:
    image: nginx:alpine
    container_name: resonance_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  database_data:
